CarProje/Models/ErrorViewModel.cs
using System;

namespace CarProje.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarProje/Controllers/HomeController.cs
using CarProje.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CarProje.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarProje/Controllers/PieceController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.Repository;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarProje.Controllers
{
    public class PieceController : Controller
    {
        PieceManager pm = new PieceManager(new PieceRepo());
        Context DB = new Context();
        public IActionResult Index()
        {
            var values = pm.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult PieceAdd()
        {
            return View();
        }
        [HttpPost]
        public IActionResult PieceAdd(Piece piece)
        {
            pm.TAdd(piece);
            return RedirectToAction("Index");
        }

        public IActionResult PieceDelete(int id)
        {
            var piece = pm.GetById(id);
            pm.TDelete(piece);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult PieceEdit(int id)
        {
            var piece = pm.GetById(id);
            return View(piece);
        }
        [HttpPost]
        public IActionResult PieceEdit(Piece piece)
        {
            PieceValidation pw = new PieceValidation();
            ValidationResult results = pw.Validate(piece);
            if (results.IsValid)
            {
                pm.TUpdate(piece);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }
            return View();
        }
    }
}

CarProje/Controllers/ProductController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.Repository;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarProje.Controllers
{
    public class ProductController : Controller
    {
        ProductManager pm = new ProductManager(new ProductRepo());
        PieceManager bm = new PieceManager(new PieceRepo());
        Context c = new Context();
        public IActionResult Index()
        {
            var values = pm.GetProductListPiece();
            return View(values);
        }
        [HttpGet]
        public IActionResult ProductAdd()

        {
            //Yedek parça Id'sini seçebilmek için yazılan sorgu.

            List<SelectListItem> piecevalues = (from x in bm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.PieceName,
                                                    Value = x.PieceID.ToString()
                                                }).ToList();
            //Viewbag kullanarak piecevalue değişkeninden gelen değerleri dropdona taşıyabiliriz.
            ViewBag.v1 = piecevalues;

            return View();
        }
        [HttpPost]
        public IActionResult ProductAdd(Product product)
        {
            pm.TAdd(product);
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult EditProduct(int id)
        {
            var product = pm.GetById(id);
            List<SelectListItem> productvalues = (from x in bm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.PieceName,
                                                      Value = x.PieceID.ToString()

                                                  }).ToList();
            ViewBag.v2 = productvalues;
            return View(product);
        }
        [HttpPost]
        public IActionResult EditProduct(Product product)
        {
            pm.TUpdate(product);
            return RedirectToAction("Index");
        }
         
        public IActionResult DeleteProduct(int id)
        {
            var productvalue = pm.GetById(id);
            pm.TDelete(productvalue);
            return RedirectToAction("Index");
        }
    }
}

CarProje/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Creative - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/Anasayfa/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">

    <header class="masthead">
        <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-end">
                    <h1 class="text-white font-weight-bold">Araba Hastanesine Hoşgeldiniz</h1>
                    <hr class="divider" />
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 mb-5">Arabalarınızın orijinal parçalarıyla değiştirip,eski haline kavuşması için elimizden geleni yapıyoruz. </p>
                    <p>Arabanız Artık Güvende!</p>
                    <a class="btn btn-dark btn-xl" href="#about">Daha Fazla</a>
                </div>
            </div>
        </div>
    </header>

    <!-- Services-->
    <section class="page-section" id="services">
        <div class="container px-4 px-lg-5">
            <h2 class="text-center mt-0">Hizmetlerimiz</h2>
            <hr class="divider" />
            <div class="row gx-4 gx-lg-5">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Parça Değişimi</h3>
                        <p class="text-muted mb-0">Orijinal parçalarla arabanızı yeniden yapılandırıyoruz!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Sigorta</h3>
                        <p class="text-muted mb-0">Tüm sigorta işlemleriniz bizden.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Kasko</h3>
                        <p class="text-muted mb-0">Bayimizden aldığınız araçların herhangi birinde parça değişiminda kaskonuzu bozmuyoruz.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Hastanemiz</h3>
                        <p class="text-muted mb-0">Arabanıza hakettiği değeri eriyoruz!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
  
</body>
</html>

CarProje/Views/Piece/Index.cshtml
@using EntityLayer.Concrete
@model List<Piece>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<div class="col-11">
    <div class="container pt-2">
        <table class="m-0 table border-left-warning table-bordered dataTable" id="dataTable" style="overflow-y:scroll">
            <thead>
                <tr role="row" class="border-dark">
                    <th  class="border-bottom-warning" style="width: 67px; height:10px; " colspan="1">#</th>
                    <th class="border-bottom-warning" style="width: 67px; height: 10px;">Parça Kodu</th>
                    <th class="border-bottom-warning" style="width: 67px; height: 10px;">Parça Adı</th>
                    <th class="border-bottom-warning" style="width: 67px; height: 10px;">Fiyat</th>
                    <th class="border-bottom-warning" style="width: 67px; height: 10px;">Detaylar </th>
                    <th class="border-bottom-warning" style="width: 67px; height: 10px;">Sil</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr class="border-bottom-warning">
                    <td>@item.PieceID</td>
                    <td>@item.PieceCode</td>
                    <td>@item.PieceName</td>
                    <td>@item.PiecePrice</td>
                    <td><a href="/Piece/PieceEdit/@item.PieceID" class="btn btn-dark">Düzenle</a></td>
                    <td><a href="/Piece/PieceDelete/@item.PieceID" class="btn btn-dark">Sil</a></td>
                </tr>
            }

        </table>
        <br />
        <a href="/Piece/PieceAdd" class="col-md-12 btn btn-outline-dark">Yeni Parça Ekle</a>
        <br />
    </div>
    <br />
</div>

CarProje/Views/Piece/PieceAdd.cshtml
@model EntityLayer.Concrete.Piece

@{
    ViewData["Title"] = "PieceAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-group row">
                <label asp-for="PieceCode" class="col-2 text-dark"><i class="fa-solid fa-bars"></i> Parça Kodu</label>
                <input asp-for="PieceCode" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="PieceName" class="col-2 text-dark"><i class="fa-solid fa-file-signature"></i> Ürün Adı</label>
                <input asp-for="PieceName" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="PiecePrice" class="col-2 text-dark"><i class="fa-solid fa-tag"></i>Ürün Fiyatı</label>
                <input asp-for="PiecePrice" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <button class="col-md-11 btn btn-outline-dark"> Ekle </button>
            </div>
        </form>
    </div>
</div>

CarProje/Views/Piece/PieceEdit.cshtml
@model EntityLayer.Concrete.Piece
@{
    ViewData["Title"] = "PieceEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="card-body">
        <form asp-controller="Piece" asp-action="PieceEdit" method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-group row">
                <label asp-for="PieceID" class="col-2 text-dark"><i class="fa-solid fa-bars"></i> Parça ID</label>
                <input asp-for="PieceID" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="PieceCode" class="col-2 text-dark"><i class="fa-solid fa-file-signature"></i> Parça Kodu</label>
                <input asp-for="PieceCode" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="PieceName" class="col-2 text-dark"><i class="fa-solid fa-file-signature"></i> Parça Adı</label>
                <input asp-for="PieceName" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="PiecePrice" class="col-2 text-dark"><i class="fa-solid fa-tag"></i>Parça Fiyatı</label>
                <input asp-for="PiecePrice" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <button class="col-md-11 btn btn-outline-dark"> Güncelle</button>
            </div>
        </form>
    </div>

    

</div>

CarProje/Views/Product/EditProduct.cshtml
@model EntityLayer.Concrete.Product
@{
    ViewData["Title"] = "EditProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="card-body">
        <form asp-controller="Product" asp-action="EditProduct" method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-group row">
                <label asp-for="ProductID" class="col-2 text-dark"><i class="fa-solid fa-bars"></i> Ürün ID</label>
                <input asp-for="ProductID" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="ProductCode" class="col-2 text-dark"><i class="fa-solid fa-file-signature"></i> Ürün Kodu</label>
                <input asp-for="ProductCode" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="ProductName" class="col-2 text-dark"><i class="fa-solid fa-file-signature"></i> Ürün Adı</label>
                <input asp-for="ProductName" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="ProductPrice" class="col-2 text-dark"><i class="fa-solid fa-tag"></i>Ürün Fiyatı</label>
                <input asp-for="ProductPrice" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="PieceID" class="col-2 text-dark"><i class="fa-solid fa-tag"></i>Yedek Parça</label>
                <select asp-for="PieceID" asp-items="ViewBag.v2" class="col-9">
                </select>

            </div>
            <br />
            <div class="form-group row">
                <button class="col-md-11 btn btn-outline-dark"> Güncelle</button>
            </div>
        </form>
    </div>



</div>

CarProje/Views/Product/Index.cshtml
@using EntityLayer.Concrete
@model List<Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-11">
    <div class="container pt-2">
        <table class="m-0 table border-left-warning table-bordered dataTable" id="dataTable" style="overflow-y:scroll">
            <thead>
                <tr role="row" class="border-dark">
                    <th class="border-bottom-warning" style="width: 67px; height:10px;" colspan="1">#</th>
                    <th class="border-bottom-warning" style="width: 67px; height:10px;">Ürün Kodu</th>
                    <th class="border-bottom-warning" style="width: 67px; height:10px;">Ürün Adı</th>
                    <th class="border-bottom-warning" style="width: 67px; height:10px;">Fiyat</th>
                    <th class="border-bottom-warning" style="width: 67px; height:10px;">Yedek Parça</th>
                    <th class="border-bottom-warning" style="width: 67px; height:10px;">Detaylar</th>
                    <th class="border-bottom-warning" style="width: 67px; height:10px;">Sil</th>

                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.ProductID</th>
                    <td>@item.ProductCode</td>
                    <td>@item.ProductName</td>
                    <td>@item.ProductPrice</td>
                    <td>@item.Piece.PieceName</td>
                    <td><a href="/Product/EditProduct/@item.ProductID" class="btn btn-dark">Detaylar</a></td>
                    <td><a href="/Product/DeleteProduct/@item.ProductID" class="btn btn-dark">Sil</a></td>
                </tr>
            }

        </table>
        <br />
        <a href="/Product/ProductAdd/" class="col-md-12 btn btn-outline-dark">Yeni Ürün Ekle</a>
    </div>
    <br />
</div>

CarProje/Views/Product/ProductAdd.cshtml
@model EntityLayer.Concrete.Product
@{
    ViewData["Title"] = "ProductAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">

    <div class="card-body">
        <form method="POST">
            <div asp-validation-summary="All"></div>
            <div class="form-group row">
                <label asp-for="ProductCode" class="col-2 text-dark"><i class="fa-solid fa-bars"></i> Ürün Kodu</label>
                <input asp-for="ProductCode" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="ProductName" class="col-2 text-dark"><i class="fa-solid fa-file-signature"></i>Ürün ismi</label>
                <input asp-for="ProductName" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="ProductPrice" class="col-2 text-dark"><i class="fa-solid fa-tag"></i>Ürün Fiyatı</label>
                <input asp-for="ProductPrice" class="col-9" />
            </div>
            <br />
            <div class="form-group row">
                <label asp-for="PieceID" class="col-2 text-dark"><i class="fa-solid fa-tag"></i>Yedek Parça</label>
                <select asp-for="PieceID" asp-items="ViewBag.v1" class="col-9">
                </select>

            </div>
            <br />
            <div class="form-group row">
                <button class="col-md-11 btn btn-outline-dark"> Ekle </button>
            </div>
        </form>
    </div>
</div>

CarProje/Views/Shared/_HeaderPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/Home/Index/">Araba Hastanesi</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="/Home/Index/">
                        Anasayfa
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Product/Index/">Ürünlerimiz</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Piece/Index/">Parçalarımız</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Hakkımızda</a>
                </li>

            </ul>
            <form class="d-flex">
                <input class="form-control me-sm-2" type="text" placeholder="Ara">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Ara</button>
            </form>
        </div>
    </div>
</nav>

CarProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Araba Hastanesi</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    @await Html.PartialAsync("~/Views/Shared/_HeaderPartial.cshtml")
    <!-- Navigation-->
    <!-- Masthead--> @RenderBody()
    @*<header class="masthead">

        </header>*@

    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Bize Ulaşın</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
            <!-- * * * * * * * * * * * * * * *-->
            <!-- * * SB Forms Contact Form * *-->
            <!-- * * * * * * * * * * * * * * *-->
            <!-- This form is pre-integrated with SB Forms.-->
            <!-- To make this form functional, sign up at-->
            <!-- https://startbootstrap.com/solution/contact-forms-->
            <!-- to get an API token!-->
            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                <div class="row align-items-stretch mb-5">
                    <div class="col-md-6">
                        <div class="form-group">
                            <!-- Name input-->
                            <input class="form-control" id="name" type="text" placeholder="İsim *" data-sb-validations="required" />
                            <div class="invalid-feedback" data-sb-feedback="name:required">Lütfen İsim Giriniz</div>
                        </div>
                        <div class="form-group">
                            <!-- Email address input-->
                            <input class="form-control" id="email" type="email" placeholder="Email *" data-sb-validations="required,email" />
                            <div class="invalid-feedback" data-sb-feedback="email:email">Lütfen Mail Adresinizi Giriniz..</div>
                        </div>
                        <div class="form-group mb-md-0">
                            <!-- Phone number input-->
                            <input class="form-control" id="phone" type="tel" placeholder="Telefon Numaranız *" data-sb-validations="required" />
                            <div class="invalid-feedback" data-sb-feedback="phone:required">Lütfen Numaranızı Giriniz.</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-textarea mb-md-0">
                            <!-- Message input-->
                            <textarea class="form-control" id="message" placeholder="Mesajınız *" data-sb-validations="required"></textarea>
                            <div class="invalid-feedback" data-sb-feedback="message:required">Lütfen Mesajınızı Giriniz.</div>
                        </div>
                    </div>
                </div>
                <!-- Submit success message-->
                <!---->
                <!-- This is what your users will see when the form-->
                <!-- has successfully submitted-->
                <div class="d-none" id="submitSuccessMessage">
                    <div class="text-center text-white mb-3">
                        <div class="fw-bolder">Form submission successful!</div>
                        To activate this form, sign up at
                        <br />
                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                    </div>
                </div>
                <!-- Submit error message-->
                <!---->
                <!-- This is what your users will see when there is-->
                <!-- an error submitting the form-->
                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Mesaj Gönderemediniz!</div></div>
                <!-- Submit Button-->
                <div class="text-center"><button class="btn btn-primary btn-xl text-uppercase disabled" id="submitButton" type="submit">Gönder</button></div>
            </form>
        </div>
    </section>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Araba Hastanesi 2022</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Gizlilik Politası</a>

                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>